services:
  backend:
    build:
      context: backend
      target: development
    secrets:
      - db-password
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/example
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]
  database:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - database-password
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/database-password
    expose:
      - 5432
  proxy:
    build: proxy
    ports:
      - 8080:80
    depends_on:
      - backend
  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
volumes:
  database-data:
secrets:
  database-password:
    file: database/password.txt
