version: "3.7"
services:
  backend:
    build:
      context: backend
    secrets:
      - database-password
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:${DATABASE_PASSWORD}@database:5432/example
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
  database:
    image: postgres:latest
    restart: always
    secrets:
      - database-password
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/database-password
    expose:
      - 5432
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - backend
  frontend:
    build:
      context: frontend
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
    command: [ "npm", "run", "start" ]
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
volumes:
  database-data:
secrets:
  database-password:
    file: database/password.txt
