version: '3.8'

services:
  database:
    image: postgres:16.1
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ../database:/var/lib/postgresql/data
    restart: always

  backend:
    # image: python:latest
    build:
      context: ../
      dockerfile: .docker/backend/Dockerfile
    container_name: backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ../backend:/app
    working_dir: /app
    depends_on:
      - database

  frontend:
    # image: node:latest
    build:
      context: ../
      dockerfile: .docker/frontend/Dockerfile
    container_name: frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ../frontend:/app
    working_dir: /app
    depends_on:
      - backend
